---
  
- name: Create grafana group
  become: true
  group:
    name: "{{ grafana_group }}"
    state: present

- name: Create grafana user
  become: true
  user:
    name: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    system: yes
    state: present

- name: Create download dir
  file:
    path: "{{ grafana_download_location }}"
    state: directory

- name: Download tar ball
  unarchive:
    remote_src: true
    src: "https://grafanarel.s3.amazonaws.com/builds/grafana-{{ grafana_version }}.linux-x64.tar.gz"
    dest: "{{ grafana_download_location }}"
    creates: "{{ grafana_download_dir }}"

- name: Move files to install dir
  become: true
  shell: "mv {{ grafana_download_dir }}/ {{ grafana_install_location }}/"
  args:
    creates: "{{ grafana_install_location }}"

- name: Set permissions
  become: true
  file:
    path: "{{ grafana_install_location }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    recurse: true

- name: Link to binary
  become: true
  file:
    src: "{{ grafana_install_location}}/bin/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
  with_items:
    - grafana-cli
    - grafana-server

- name: Copy service file
  become: true
  template:
    src: grafana.service.j2
    dest: /etc/systemd/system/grafana.service

- name: Reload
  become: true
  shell: systemctl daemon-reload

- name: Start grafana
  become: true
  service:
    name: grafana
    state: restarted
    enabled: true

