---
- hosts: all
  remote_user: ansible
  become: true

  vars_prompt:
    - name: username
      prompt: "Username to add to host"
    - name: password
      prompt: "Password"
      private: yes
      encrypt: "sha512_crypt"
      salt_size: 8

  tasks:
   - name: Create User
     user:
      name: "{{ username }}"
      password: '{{ password }}'
      groups: sudo
      append: yes
      state: present

