---
- hosts: all
  remote_user: root
  tasks:
   - name: "Ensure sudo is installed"
     package:
       name: sudo
       state: present

   - name: "Ensure sudo group is available"
     group:
       name: sudo
       state: present

   - name: "Allow passwordless sudo for sudoers"
     lineinfile:
       dest: /etc/sudoers
       state: present
       regexp: "^%sudo"
       line: "%sudo ALL=(ALL) NOPASSWD: ALL"

   - name: "Create ansible user"
     user: 
       name: ansible
       groups: sudo
       append: yes
       state: present

   - name: "Publish ssh key"
     authorized_key:
       user: ansible 
       key: "{{ lookup('file', '/root/.ssh/id_rsa.pub')}}"
