---

- name: Install docker
  package:
    name: docker
    state: present

- name: Enable external docker API access
  copy:
    src: files/override.conf
    dest: /etc/systemd/system/docker.service.d/override.conf

- name: Autostart docker
  become: true
  service:
    name: docker
    state: started
    enabled: true
