---
- name: Create kibana group
  become: true
  group:
    name: "{{ kibana_group }}"
    state: present

- name: Create kibana user
  become: true
  user:
    name: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
    system: yes
    state: present

- name: Download and unpack
  extract:
      remote_src: true
      src: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
      dest: "{{ kibana_install_dir }}"

- name: Copy config
  become: true
  template:
      src: kibana.yml.j2
      dest: "{{ kibana_location }}/config/kibana.yml"
 
- name: Copy service file
  become: true
  template:
    src: kibana.service.j2
    dest: /etc/systemd/system/kibana.service

- name: Reload systemd
  become: true
  shell: systemctl daemon-reload

- name: Start kibana
  become: true
  service:
    name: kibana
    state: started
    enabled: true
   
