---
- name: Install docker
  become: true
  package:
    name: docker
    state: present

- name: Ensure docker service dir is available
  become: true
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Enable external docker API access
  become: true
  copy:
    src: files/override.conf
    dest: /etc/systemd/system/docker.service.d/override.conf
  notify: Restart docker

- name: Autostart docker
  become: true
  service:
    name: docker
    enabled: true
    state: started
