---

- name: Install vim
  become: true
  package:
    name: vim
    state: present

- name: Copy vimrc 
  become: true
  get_url:
    url: https://raw.githubusercontent.com/lenny151/dotfiles/master/.vimrc
    dest: "{{ vim_user_home }}/.vimrc"
